// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDqvMoQ0n9Is_kUkpvTB-Hf1xL-Trj8g0',
    appId: '1:582382138356:web:3d17b14a4641684216ffa1',
    messagingSenderId: '582382138356',
    projectId: 'wealthway-402b4',
    authDomain: 'wealthway-402b4.firebaseapp.com',
    storageBucket: 'wealthway-402b4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjPQfdIWf6UGX6Hd5h1R-BxCtagNzvyW4',
    appId: '1:582382138356:android:aa3711fefe8aac2f16ffa1',
    messagingSenderId: '582382138356',
    projectId: 'wealthway-402b4',
    storageBucket: 'wealthway-402b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPxNz5_4MT2OXznjNtUM0ic-iD4FCwlTQ',
    appId: '1:582382138356:ios:40167a73fa2c3bc916ffa1',
    messagingSenderId: '582382138356',
    projectId: 'wealthway-402b4',
    storageBucket: 'wealthway-402b4.firebasestorage.app',
    iosBundleId: 'com.example.sqlitedemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPxNz5_4MT2OXznjNtUM0ic-iD4FCwlTQ',
    appId: '1:582382138356:ios:40167a73fa2c3bc916ffa1',
    messagingSenderId: '582382138356',
    projectId: 'wealthway-402b4',
    storageBucket: 'wealthway-402b4.firebasestorage.app',
    iosBundleId: 'com.example.sqlitedemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDqvMoQ0n9Is_kUkpvTB-Hf1xL-Trj8g0',
    appId: '1:582382138356:web:b4282007a9b836a216ffa1',
    messagingSenderId: '582382138356',
    projectId: 'wealthway-402b4',
    authDomain: 'wealthway-402b4.firebaseapp.com',
    storageBucket: 'wealthway-402b4.firebasestorage.app',
  );

}